"""Add currency table with ISO 4217 seed data.

Revision ID: 039
Revises: 038
Create Date: 2026-03-10

"""

from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "039"
down_revision: Union[str, None] = "038"
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None

# fmt: off
CURRENCIES: list[tuple[str, str, str]] = [
    # (iso_4217, symbol, name)
    ("AED", "د.إ",   "UAE Dirham"),
    ("AFN", "؋",     "Afghan Afghani"),
    ("ALL", "L",     "Albanian Lek"),
    ("AMD", "֏",     "Armenian Dram"),
    ("ANG", "ƒ",     "Netherlands Antillean Guilder"),
    ("AOA", "Kz",    "Angolan Kwanza"),
    ("ARS", "$",     "Argentine Peso"),
    ("AUD", "A$",    "Australian Dollar"),
    ("AWG", "ƒ",     "Aruban Florin"),
    ("AZN", "₼",     "Azerbaijani Manat"),
    ("BAM", "KM",    "Bosnia-Herzegovina Convertible Mark"),
    ("BBD", "$",     "Barbadian Dollar"),
    ("BDT", "৳",     "Bangladeshi Taka"),
    ("BGN", "лв",    "Bulgarian Lev"),
    ("BHD", "BD",    "Bahraini Dinar"),
    ("BIF", "Fr",    "Burundian Franc"),
    ("BMD", "$",     "Bermudian Dollar"),
    ("BND", "$",     "Brunei Dollar"),
    ("BOB", "Bs.",   "Bolivian Boliviano"),
    ("BRL", "R$",    "Brazilian Real"),
    ("BSD", "$",     "Bahamian Dollar"),
    ("BTN", "Nu",    "Bhutanese Ngultrum"),
    ("BWP", "P",     "Botswana Pula"),
    ("BYN", "Br",    "Belarusian Ruble"),
    ("BZD", "$",     "Belize Dollar"),
    ("CAD", "CA$",   "Canadian Dollar"),
    ("CDF", "Fr",    "Congolese Franc"),
    ("CHF", "Fr",    "Swiss Franc"),
    ("CLP", "$",     "Chilean Peso"),
    ("CNY", "¥",     "Chinese Renminbi Yuan"),
    ("COP", "$",     "Colombian Peso"),
    ("CRC", "₡",     "Costa Rican Colón"),
    ("CUP", "$",     "Cuban Peso"),
    ("CVE", "$",     "Cape Verdean Escudo"),
    ("CZK", "Kč",    "Czech Koruna"),
    ("DJF", "Fr",    "Djiboutian Franc"),
    ("DKK", "kr.",   "Danish Krone"),
    ("DOP", "$",     "Dominican Peso"),
    ("DZD", "دج",    "Algerian Dinar"),
    ("EGP", "£",     "Egyptian Pound"),
    ("ERN", "Nfk",   "Eritrean Nakfa"),
    ("ETB", "Br",    "Ethiopian Birr"),
    ("EUR", "€",     "Euro"),
    ("FJD", "$",     "Fijian Dollar"),
    ("FKP", "£",     "Falkland Islands Pound"),
    ("GBP", "£",     "British Pound Sterling"),
    ("GEL", "₾",     "Georgian Lari"),
    ("GHS", "₵",     "Ghanaian Cedi"),
    ("GIP", "£",     "Gibraltar Pound"),
    ("GMD", "D",     "Gambian Dalasi"),
    ("GNF", "Fr",    "Guinean Franc"),
    ("GTQ", "Q",     "Guatemalan Quetzal"),
    ("GYD", "$",     "Guyanese Dollar"),
    ("HKD", "HK$",   "Hong Kong Dollar"),
    ("HNL", "L",     "Honduran Lempira"),
    ("HTG", "G",     "Haitian Gourde"),
    ("HUF", "Ft",    "Hungarian Forint"),
    ("IDR", "Rp",    "Indonesian Rupiah"),
    ("ILS", "₪",     "Israeli New Shekel"),
    ("INR", "₹",     "Indian Rupee"),
    ("IQD", "ع.د",   "Iraqi Dinar"),
    ("IRR", "﷼",     "Iranian Rial"),
    ("ISK", "kr",    "Icelandic Króna"),
    ("JMD", "$",     "Jamaican Dollar"),
    ("JOD", "JD",    "Jordanian Dinar"),
    ("JPY", "¥",     "Japanese Yen"),
    ("KES", "KSh",   "Kenyan Shilling"),
    ("KGS", "с",     "Kyrgyzstani Som"),
    ("KHR", "៛",     "Cambodian Riel"),
    ("KMF", "Fr",    "Comorian Franc"),
    ("KPW", "₩",     "North Korean Won"),
    ("KRW", "₩",     "South Korean Won"),
    ("KWD", "KD",    "Kuwaiti Dinar"),
    ("KYD", "$",     "Cayman Islands Dollar"),
    ("KZT", "₸",     "Kazakhstani Tenge"),
    ("LAK", "₭",     "Lao Kip"),
    ("LBP", "£",     "Lebanese Pound"),
    ("LKR", "₨",     "Sri Lankan Rupee"),
    ("LRD", "$",     "Liberian Dollar"),
    ("LSL", "L",     "Lesotho Loti"),
    ("LYD", "LD",    "Libyan Dinar"),
    ("MAD", "MAD",   "Moroccan Dirham"),
    ("MDL", "L",     "Moldovan Leu"),
    ("MGA", "Ar",    "Malagasy Ariary"),
    ("MKD", "ден",   "Macedonian Denar"),
    ("MMK", "K",     "Myanmar Kyat"),
    ("MNT", "₮",     "Mongolian Tögrög"),
    ("MOP", "P",     "Macanese Pataca"),
    ("MRU", "UM",    "Mauritanian Ouguiya"),
    ("MUR", "₨",     "Mauritian Rupee"),
    ("MVR", "Rf",    "Maldivian Rufiyaa"),
    ("MWK", "MK",    "Malawian Kwacha"),
    ("MXN", "$",     "Mexican Peso"),
    ("MYR", "RM",    "Malaysian Ringgit"),
    ("MZN", "MT",    "Mozambican Metical"),
    ("NAD", "$",     "Namibian Dollar"),
    ("NGN", "₦",     "Nigerian Naira"),
    ("NIO", "C$",    "Nicaraguan Córdoba"),
    ("NOK", "kr",    "Norwegian Krone"),
    ("NPR", "₨",     "Nepalese Rupee"),
    ("NZD", "NZ$",   "New Zealand Dollar"),
    ("OMR", "﷼",     "Omani Rial"),
    ("PAB", "B/.",   "Panamanian Balboa"),
    ("PEN", "S/.",   "Peruvian Sol"),
    ("PGK", "K",     "Papua New Guinean Kina"),
    ("PHP", "₱",     "Philippine Peso"),
    ("PKR", "₨",     "Pakistani Rupee"),
    ("PLN", "zł",    "Polish Złoty"),
    ("PYG", "Gs",    "Paraguayan Guaraní"),
    ("QAR", "﷼",     "Qatari Riyal"),
    ("RON", "lei",   "Romanian Leu"),
    ("RSD", "din",   "Serbian Dinar"),
    ("RUB", "₽",     "Russian Ruble"),
    ("RWF", "Fr",    "Rwandan Franc"),
    ("SAR", "﷼",     "Saudi Riyal"),
    ("SBD", "$",     "Solomon Islands Dollar"),
    ("SCR", "₨",     "Seychellois Rupee"),
    ("SDG", "LS",    "Sudanese Pound"),
    ("SEK", "kr",    "Swedish Krona"),
    ("SGD", "S$",    "Singapore Dollar"),
    ("SHP", "£",     "Saint Helenian Pound"),
    ("SLE", "Le",    "Sierra Leonean Leone"),
    ("SOS", "Sh",    "Somali Shilling"),
    ("SRD", "$",     "Surinamese Dollar"),
    ("SSP", "£",     "South Sudanese Pound"),
    ("STN", "Db",    "São Tomé and Príncipe Dobra"),
    ("SVC", "₡",     "Salvadoran Colón"),
    ("SYP", "£",     "Syrian Pound"),
    ("SZL", "L",     "Swazi Lilangeni"),
    ("THB", "฿",     "Thai Baht"),
    ("TJS", "SM",    "Tajikistani Somoni"),
    ("TMT", "T",     "Turkmenistani Manat"),
    ("TND", "DT",    "Tunisian Dinar"),
    ("TOP", "T$",    "Tongan Paʻanga"),
    ("TRY", "₺",     "Turkish Lira"),
    ("TTD", "$",     "Trinidad and Tobago Dollar"),
    ("TWD", "NT$",   "New Taiwan Dollar"),
    ("TZS", "Sh",    "Tanzanian Shilling"),
    ("UAH", "₴",     "Ukrainian Hryvnia"),
    ("UGX", "Sh",    "Ugandan Shilling"),
    ("USD", "$",     "US Dollar"),
    ("UYU", "$",     "Uruguayan Peso"),
    ("UZS", "so'm",  "Uzbekistani Som"),
    ("VES", "Bs.S",  "Venezuelan Bolívar Soberano"),
    ("VND", "₫",     "Vietnamese Đồng"),
    ("VUV", "Vt",    "Vanuatu Vatu"),
    ("WST", "T",     "Samoan Tālā"),
    ("XAF", "Fr",    "Central African CFA Franc"),
    ("XCD", "$",     "East Caribbean Dollar"),
    ("XOF", "Fr",    "West African CFA Franc"),
    ("XPF", "Fr",    "CFP Franc"),
    ("YER", "﷼",     "Yemeni Rial"),
    ("ZAR", "R",     "South African Rand"),
    ("ZMW", "ZK",    "Zambian Kwacha"),
    ("ZWL", "$",     "Zimbabwean Dollar"),
]
# fmt: on


def upgrade() -> None:
    currency_table = op.create_table(
        "currency",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=False), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("iso_4217", sa.String(3), nullable=False),
        sa.Column("symbol", sa.String(10), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
    )
    op.create_index("ix_currency_active", "currency", ["active"])
    op.create_index("ix_currency_iso_4217", "currency", ["iso_4217"], unique=True)

    op.bulk_insert(
        currency_table,
        [{"iso_4217": iso, "symbol": sym, "name": name} for iso, sym, name in CURRENCIES],
    )


def downgrade() -> None:
    op.drop_index("ix_currency_iso_4217", table_name="currency")
    op.drop_index("ix_currency_active", table_name="currency")
    op.drop_table("currency")
