"""add user_customer table

Revision ID: 05ddb19f71fb
Revises: ae05512df4ff
Create Date: 2026-04-01 18:48:44.012251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ddb19f71fb'
down_revision: Union[str, None] = 'ae05512df4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_customer',
    sa.Column('user_id', sa.String(36), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('allow_insight', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_prediction', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_customer_new', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_customer_view', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_sale_view', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_sale_analytics', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_outlet_new', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_outlet_view', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_outlet_analytics', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_outlet_group', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_outlet_bulk', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_pad_add', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_pad_view', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_filter_add', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_pad_predefined_view', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_financials_date_override', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_financials_price_history', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_financials_bulk', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_configuration_profile', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_configuration_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_configuration_explore', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_ai_models', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ba_users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'customer_id', name='uq_user_customer_user_customer')
    )
    op.create_index(op.f('ix_user_customer_active'), 'user_customer', ['active'], unique=False)
    op.create_index(op.f('ix_user_customer_customer_id'), 'user_customer', ['customer_id'], unique=False)
    op.create_index(op.f('ix_user_customer_user_id'), 'user_customer', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_customer_user_id'), table_name='user_customer')
    op.drop_index(op.f('ix_user_customer_customer_id'), table_name='user_customer')
    op.drop_index(op.f('ix_user_customer_active'), table_name='user_customer')
    op.drop_table('user_customer')
    # ### end Alembic commands ###
