"""add insights_system_prompt to customer_configuration

Revision ID: 0e21c8e46606
Revises: 98bc4169a37b
Create Date: 2026-04-01 17:12:03.882609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e21c8e46606'
down_revision: Union[str, None] = '98bc4169a37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_configuration', sa.Column('insights_system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_configuration', 'insights_system_prompt')
    # ### end Alembic commands ###
