"""add insights_hidden_prompt to customer_configuration

Revision ID: ae05512df4ff
Revises: 0e21c8e46606
Create Date: 2026-04-01 17:20:41.223645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae05512df4ff'
down_revision: Union[str, None] = '0e21c8e46606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_configuration', sa.Column('insights_hidden_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_configuration', 'insights_hidden_prompt')
    # ### end Alembic commands ###
