"""add llm token token_model token_llm tables

Revision ID: cd3e507c9147
Revises: e873d84747da
Create Date: 2026-03-31 13:00:59.965090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd3e507c9147'
down_revision: Union[str, None] = 'e873d84747da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_active'), 'llm', ['active'], unique=False)
    op.create_table('token',
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('used', sa.BigInteger(), nullable=False),
    sa.Column('available', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_active'), 'token', ['active'], unique=False)
    op.create_index(op.f('ix_token_customer_id'), 'token', ['customer_id'], unique=False)
    op.create_table('token_llm',
    sa.Column('token_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('llm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('used', sa.BigInteger(), nullable=False),
    sa.Column('available', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['llm_id'], ['llm.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_llm_active'), 'token_llm', ['active'], unique=False)
    op.create_index(op.f('ix_token_llm_llm_id'), 'token_llm', ['llm_id'], unique=False)
    op.create_index(op.f('ix_token_llm_token_id'), 'token_llm', ['token_id'], unique=False)
    op.create_table('token_model',
    sa.Column('token_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prediction_engine_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('used', sa.BigInteger(), nullable=False),
    sa.Column('available', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_engine_id'], ['prediction_engine.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_model_active'), 'token_model', ['active'], unique=False)
    op.create_index(op.f('ix_token_model_prediction_engine_id'), 'token_model', ['prediction_engine_id'], unique=False)
    op.create_index(op.f('ix_token_model_token_id'), 'token_model', ['token_id'], unique=False)
    op.drop_index(op.f('ba_sessions_token_key'), table_name='ba_sessions')
    op.drop_table('ba_sessions')
    op.drop_table('ba_accounts')
    op.drop_table('ba_two_factors')
    op.drop_table('ba_verifications')
    op.drop_index(op.f('ba_users_email_key'), table_name='ba_users')
    op.drop_table('ba_users')
    op.create_index(op.f('ix_covariate_outlet_active'), 'covariate_outlet', ['active'], unique=False)
    op.create_index(op.f('ix_covariates_active'), 'covariates', ['active'], unique=False)
    op.create_index(op.f('ix_financial_dates_active'), 'financial_dates', ['active'], unique=False)
    op.create_index(op.f('ix_fine_tunes_active'), 'fine_tunes', ['active'], unique=False)
    op.create_index(op.f('ix_last_prediction_active'), 'last_prediction', ['active'], unique=False)
    op.create_index(op.f('ix_outlet_financial_dates_active'), 'outlet_financial_dates', ['active'], unique=False)
    op.create_index(op.f('ix_outlet_financials_active'), 'outlet_financials', ['active'], unique=False)
    op.drop_index(op.f('ix_pad_dates_date'), table_name='pad_dates')
    op.create_index(op.f('ix_pad_dates_active'), 'pad_dates', ['active'], unique=False)
    op.create_index(op.f('ix_pads_active'), 'pads', ['active'], unique=False)
    op.create_index(op.f('ix_predefined_pad_active'), 'predefined_pad', ['active'], unique=False)
    op.create_index(op.f('ix_predefined_pad_date_active'), 'predefined_pad_date', ['active'], unique=False)
    op.create_index(op.f('ix_prediction_outlets_active'), 'prediction_outlets', ['active'], unique=False)
    op.create_index(op.f('ix_prediction_strategies_active'), 'prediction_strategies', ['active'], unique=False)
    op.create_index(op.f('ix_predictions_active'), 'predictions', ['active'], unique=False)
    op.drop_index(op.f('ix_sales_customer_outlet_date'), table_name='sales')
    op.create_index(op.f('ix_sales_filters_active'), 'sales_filters', ['active'], unique=False)
    op.create_index(op.f('ix_simulation_dates_active'), 'simulation_dates', ['active'], unique=False)
    op.create_index(op.f('ix_simulation_strategies_active'), 'simulation_strategies', ['active'], unique=False)
    op.create_index(op.f('ix_simulations_active'), 'simulations', ['active'], unique=False)
    op.drop_constraint(op.f('uq_task_records_task_id'), 'task_records', type_='unique')
    op.drop_index(op.f('ix_task_records_task_id'), table_name='task_records')
    op.create_index(op.f('ix_task_records_task_id'), 'task_records', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_records_task_id'), table_name='task_records')
    op.create_index(op.f('ix_task_records_task_id'), 'task_records', ['task_id'], unique=False)
    op.create_unique_constraint(op.f('uq_task_records_task_id'), 'task_records', ['task_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_simulations_active'), table_name='simulations')
    op.drop_index(op.f('ix_simulation_strategies_active'), table_name='simulation_strategies')
    op.drop_index(op.f('ix_simulation_dates_active'), table_name='simulation_dates')
    op.drop_index(op.f('ix_sales_filters_active'), table_name='sales_filters')
    op.create_index(op.f('ix_sales_customer_outlet_date'), 'sales', ['customer_id', 'outlet_id', 'date'], unique=False)
    op.drop_index(op.f('ix_predictions_active'), table_name='predictions')
    op.drop_index(op.f('ix_prediction_strategies_active'), table_name='prediction_strategies')
    op.drop_index(op.f('ix_prediction_outlets_active'), table_name='prediction_outlets')
    op.drop_index(op.f('ix_predefined_pad_date_active'), table_name='predefined_pad_date')
    op.drop_index(op.f('ix_predefined_pad_active'), table_name='predefined_pad')
    op.drop_index(op.f('ix_pads_active'), table_name='pads')
    op.drop_index(op.f('ix_pad_dates_active'), table_name='pad_dates')
    op.create_index(op.f('ix_pad_dates_date'), 'pad_dates', ['date'], unique=False)
    op.drop_index(op.f('ix_outlet_financials_active'), table_name='outlet_financials')
    op.drop_index(op.f('ix_outlet_financial_dates_active'), table_name='outlet_financial_dates')
    op.drop_index(op.f('ix_last_prediction_active'), table_name='last_prediction')
    op.drop_index(op.f('ix_fine_tunes_active'), table_name='fine_tunes')
    op.drop_index(op.f('ix_financial_dates_active'), table_name='financial_dates')
    op.drop_index(op.f('ix_covariates_active'), table_name='covariates')
    op.drop_index(op.f('ix_covariate_outlet_active'), table_name='covariate_outlet')
    op.create_table('ba_users',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('emailVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('twoFactorEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ba_users_pkey'))
    )
    op.create_index(op.f('ba_users_email_key'), 'ba_users', ['email'], unique=True)
    op.create_table('ba_verifications',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ba_verifications_pkey'))
    )
    op.create_table('ba_two_factors',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('secret', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('backupCodes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['ba_users.id'], name=op.f('ba_two_factors_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ba_two_factors_pkey'))
    )
    op.create_table('ba_accounts',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accountId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('providerId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accessToken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refreshToken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('idToken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accessTokenExpiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('refreshTokenExpiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['ba_users.id'], name=op.f('ba_accounts_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ba_accounts_pkey'))
    )
    op.create_table('ba_sessions',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('ipAddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userAgent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['ba_users.id'], name=op.f('ba_sessions_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ba_sessions_pkey'))
    )
    op.create_index(op.f('ba_sessions_token_key'), 'ba_sessions', ['token'], unique=True)
    op.drop_index(op.f('ix_token_model_token_id'), table_name='token_model')
    op.drop_index(op.f('ix_token_model_prediction_engine_id'), table_name='token_model')
    op.drop_index(op.f('ix_token_model_active'), table_name='token_model')
    op.drop_table('token_model')
    op.drop_index(op.f('ix_token_llm_token_id'), table_name='token_llm')
    op.drop_index(op.f('ix_token_llm_llm_id'), table_name='token_llm')
    op.drop_index(op.f('ix_token_llm_active'), table_name='token_llm')
    op.drop_table('token_llm')
    op.drop_index(op.f('ix_token_customer_id'), table_name='token')
    op.drop_index(op.f('ix_token_active'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_llm_active'), table_name='llm')
    op.drop_table('llm')
    # ### end Alembic commands ###
