"""add llm token token_model token_llm tables

Revision ID: cd3e507c9147
Revises: e873d84747da
Create Date: 2026-03-31 13:00:59.965090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd3e507c9147'
down_revision: Union[str, None] = 'e873d84747da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_active'), 'llm', ['active'], unique=False)
    op.create_table('token',
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('used', sa.BigInteger(), nullable=False),
    sa.Column('available', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_active'), 'token', ['active'], unique=False)
    op.create_index(op.f('ix_token_customer_id'), 'token', ['customer_id'], unique=False)
    op.create_table('token_llm',
    sa.Column('token_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('llm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('used', sa.BigInteger(), nullable=False),
    sa.Column('available', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['llm_id'], ['llm.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_llm_active'), 'token_llm', ['active'], unique=False)
    op.create_index(op.f('ix_token_llm_llm_id'), 'token_llm', ['llm_id'], unique=False)
    op.create_index(op.f('ix_token_llm_token_id'), 'token_llm', ['token_id'], unique=False)
    op.create_table('token_model',
    sa.Column('token_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prediction_engine_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('used', sa.BigInteger(), nullable=False),
    sa.Column('available', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_engine_id'], ['prediction_engine.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_model_active'), 'token_model', ['active'], unique=False)
    op.create_index(op.f('ix_token_model_prediction_engine_id'), 'token_model', ['prediction_engine_id'], unique=False)
    op.create_index(op.f('ix_token_model_token_id'), 'token_model', ['token_id'], unique=False)
    # NOTE: The remaining autogenerated operations (dropping the Better Auth
    # ba_* tables, recreating indexes that earlier migrations already created,
    # and dropping intentional indexes such as ix_sales_customer_outlet_date)
    # were spurious diff noise from autogenerate against a divergent database.
    # They are intentionally removed — this migration only adds the llm, token,
    # token_llm and token_model tables.
    # ### end Alembic commands ###


def downgrade() -> None:
    # Mirror of the trimmed upgrade(): only drop the four tables this
    # migration actually created.
    op.drop_index(op.f('ix_token_model_token_id'), table_name='token_model')
    op.drop_index(op.f('ix_token_model_prediction_engine_id'), table_name='token_model')
    op.drop_index(op.f('ix_token_model_active'), table_name='token_model')
    op.drop_table('token_model')
    op.drop_index(op.f('ix_token_llm_token_id'), table_name='token_llm')
    op.drop_index(op.f('ix_token_llm_llm_id'), table_name='token_llm')
    op.drop_index(op.f('ix_token_llm_active'), table_name='token_llm')
    op.drop_table('token_llm')
    op.drop_index(op.f('ix_token_customer_id'), table_name='token')
    op.drop_index(op.f('ix_token_active'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_llm_active'), table_name='llm')
    op.drop_table('llm')
    # ### end Alembic commands ###
